/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String arg[]) {
		System.out.println("this is redo for ON kim!");
	}
	//on huantingwei again
    public boolean someLibraryMethod() {
        return true;
    }
}
